# See more config options https://github.com/gakonst/foundry/tree/master/config

[default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
  "ds/=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts/contracts/",
]


[ci]
fuzz_runs = 2_000